version: '3'

services:

  nginx:
    container_name: liga_nginx
    image: nginx:1.15.2-alpine
    restart: always
    volumes:
      - ./www/laravel/:/var/www/laravel/:cached
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - laravel
      - node_admin

  node_admin:
    container_name: liga_node_admin
    image: node:8.9.4
    working_dir: /var/www/node_admin/
    command: npm run start
    volumes:
      - ./www/admin/:/var/www/node_admin/:cached

  laravel:
    container_name: liga_laravel
    image: 'ishaburov/laravel_php-fpm7.3_build:latest'
    restart: always
    working_dir: /var/www/laravel/
    volumes:
      - ${LARAVEL_PATH_HOST}:${LARAVEL_PATH_CONTAINER}:cached
    depends_on:
      - mysqldb
    ports:
      - 9000:9000

  mysqldb:
    container_name: liga_mysqldb
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=liga
      - MYSQL_USER=liga
      - MYSQL_PASSWORD=123456
    volumes:
      - ./mysql-data:/var/lib/mysql:cached
    ports:
      - 3306:3306

  adminer:
    container_name: liga_adminer
    image: adminer:latest
    restart: always
    ports:
      - 8006:8080
    depends_on:
      - mysqldb

  composer:
    container_name: liga_composer
    image: 'ishaburov/laravel_php-fpm7.3_build:latest'
    volumes:
      - ./www/laravel/:/var/www/laravel/
    working_dir: /var/www/laravel/
    command: composer install
